#!/bin/bash

# Проверяет, что строка содержит только буквенно-цифровые символы
# Удаляет недопустимые символы и сравнивает с оригиналом
validAlphaNum()
{
    validchars="$(echo $1 | sed -e 's/[^[:alnum:]]//g')"
    
    if [ $validchars = $1 ] ; then 
        return 0
    else 
        return 1
    fi
}


# Разкоментировать для тестирования
#############################
# echo -n "Enter input: "
# read input

# if ! validAlphaNum "$input" ; then 
#    echo "Only letters numbers" >&2
#    exit 1
# else 
#     echo "Input is valid"
# fi

# exit 0