#!/bin/bash

#   nicenumber -- отображает переданное число в формате представления с запятыми
# Предполагает наличие переменных:
# DD (decimal point delimiter -- разделитель дробной части) и 
# TD (thousands delimiter -- разделитель групп разрядов).
# Создает переменную nicenum с результатом, а при наличии второго аргумента
# дополнительно выводит результат в стандартный вывод.
nicenumber()
{
    integer=$(echo $1 | cut -d. -f1)    # слева от точки
    decimal=$(echo $1 | cut -d. -f2)    # справа от точки

# Проверка писутствия дроьной части
    if [ "$decimal" != "$1" ]; then 
        result="${DD:= '.'}$decimal" # Включение дробной части в результат
    fi

    thousands=$integer

    while [ $thousands -gt 999 ]; do
        remainder=$(($thousands % 1000)) # три последние значимые цифры
        while [ ${#remainder} -lt 3 ] ; do # если меньше трех знаков -
            remainder="0$remainder"        # - добавляем вперёд нули 
        done

        result="${TD:=","}${remainder}${result}" # собрать справа налево
        thousands=$(($thousands / 1000))         # остаток, если есть
    done

    nicenum="${thousands}${result}"
    if [ ! -z $2 ] ; then
        echo $nicenum
    fi
}
            
DD="."
TD=","

# Раскоментировать для проверки
#################

#while getopts "d:t:" opt; do 
#    case $opt in
#        d) DD="$OPTARG" ;;
#        t) TD="$OPTARG" ;;
#    esac
#done
#shift $(($OPTIND -1))
#
#
#if [ $# -eq 0 ] ; then
#    echo "Usage: $(basename $0) [-d c] [-t c] number"
#    echo " -d specifies the decimal point delimiter"
#    echo " -t specifies the thousands delimiter"
#    exit 0
#fi
#
#nicenumber $1 1
#
#exit 0
