#!/bin/bash

# Преобразует поле месяца в строке с датой в трхсимвольное представление

monthNumToName()
{
    case $1 in
        1 ) month="Jan" ;; 2 ) month="Feb" ;;
        3 ) month="Mar" ;; 4 ) month="Apr" ;;
        5 ) month="May" ;; 6 ) month="Jun" ;;
        7 ) month="Jul" ;; 8 ) month="Aug" ;;
        9 ) month="Sep" ;; 10) month="Oct" ;;
        11) month="Nov" ;; 12) month="Dec" ;;
        *) echo "$0: Unknown month value $1" >&2
            exit 1
    esac
    return 0
}

# Начало скрипта
############################

# Чтобы компенсировать форматы с / и -
if [ $# -eq 1 ] ; then 
set -- $(echo $1 | sed 's/[\/\-]/ /g')
fi


# меньше 3х аргументов
if [ $# -ne 3 ] ; then 
    echo "Usage: $0 month day year" >&2
    exit 1
fi

# короткий год
if [ $3 -le 99 ] ; then 
    echo "$0: expected 4-digit year value" >&2
    exit 1
fi

# удаляет цифры и проверяет на пустую строку 
if [ -z $(echo $1 | sed 's/[[:digit:]]//g') ]; then
    monthNumToName $1
else 
    month="$(echo $1 | cut -c1 | tr '[:lower:]' '[:upper:]')" # первый символ в верхний регистр
    month="$month$(echo $1 | cut -c2-3 | tr '[:upper:]' '[:lower:]' )" # остальные 2 - в нижний

fi

echo $month $2 $3

exit 0
